services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - private-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - private-network
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  database:
    image: mongo:6.0.13-jammy
    ports:
      - "27017:27017"
    networks:
      - private-network
    volumes:
      - db:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  private-network:
    driver: bridge

volumes:
  db:
    driver: local
