# This is the Docker file for the backend service with ubuntu 22.04 as the base image and its a single stage build
FROM ubuntu:22.04


WORKDIR /app


RUN apt-get update && apt-get install -y nodejs npm && \
    apt-get clean && rm -rf /var/lib/apt/lists/*



COPY package*.json .

RUN npm install

COPY . .

EXPOSE 5050

CMD [ "npm", "run", "start" ]
